//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Checkers.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CheckersEntities : DbContext
    {
        public CheckersEntities()
            : base("name=CheckersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<algorithm> algorithms { get; set; }
        public virtual DbSet<game> games { get; set; }
        public virtual DbSet<game_move> game_move { get; set; }
        public virtual DbSet<game_type> game_type { get; set; }
        public virtual DbSet<player> players { get; set; }
        public virtual DbSet<player_information> player_information { get; set; }
    }
}
