//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Checkers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_move
    {
        public int game_move_id { get; set; }
        public int game_id { get; set; }
        public string player { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public int from_position { get; set; }
        public int to_position { get; set; }
        public int beated_pieces_count { get; set; }
        public string beated_pieces { get; set; }
        public string board_after_move { get; set; }
    
        public virtual game game { get; set; }
    }
}
