//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Checkers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public game()
        {
            this.game_move = new HashSet<game_move>();
        }
    
        public int game_id { get; set; }
        public int white_player_information_id { get; set; }
        public int black_player_information_id { get; set; }
        public int game_type_id { get; set; }
        public int game_size { get; set; }
        public string game_result { get; set; }
    
        public virtual player_information player_information { get; set; }
        public virtual game_type game_type { get; set; }
        public virtual player_information player_information1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<game_move> game_move { get; set; }
    }
}
